Global:
  use_gpu: true
  epoch_num: 200
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_CLCLabNom_svtrnet_base_nom_exp_5.1/
  save_epoch_step: 1
  eval_batch_step:
    - 13880
    - 2000
  cal_metric_during_train: true
  pretrained_model: ./output/rec_CLCLabNom_svtrnet_base_nom_exp_5/best_model/model
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: null
  character_dict_path: ppocr/utils/dict/PP-Thesis/hisdoc1b_ss1_nom.txt
  max_text_length: 40
  infer_mode: false
  use_space_char: false
  save_res_path: null
  use_amp: true
  use_wandb: true
  distributed: true
  d2s_train_image_shape: [3, 32, 640]

wandb:
  project: "PP-Thesis-Rec-Main-Exp-5"
  entity: "trankim147-vnu-hcmus"
  name: "Experiment-5.1"

Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  epsilon: 1.e-8
  weight_decay: 0.05
  no_weight_decay_name: norm
  one_dim_param_no_weight_decay: True
  lr:
    name: Cosine
    learning_rate: 0.00075 # 12gpus 96bs
    warmup_epoch: 5

Architecture:
  model_type: rec
  algorithm: SVTR
  Transform: null
  Backbone:
    name: SVTRNet
    img_size:
      - 32
      - 640
    out_char_num: 40 # W//4 or W//8 or W/12
    out_channels: 256
    patch_merging: Conv
    patch_size: [4, 8]
    embed_dim:
      - 128
      - 256
      - 384
    depth:
      - 3
      - 6
      - 9
    num_heads:
      - 4
      - 8
      - 12
    mixer:
      - Local
      - Local
      - Local
      - Local
      - Local
      - Local
      - Local
      - Local
      - Global
      - Global
      - Global
      - Global
      - Global
      - Global
      - Global
      - Global
      - Global
      - Global
    local_mixer:
      - - 7
        - 11
      - - 7
        - 11
      - - 7
        - 11
    last_stage: true
    prenorm: false
  Neck:
    name: SequenceEncoder
    encoder_type: svtr
    dims: 240
    depth: 2
    hidden_dims: 240
    kernel_size: [1, 3]
  Head:
    name: CTCHead

Loss:
  name: KLMultiLoss
  weight_1: 1.0
  weight_2: 1.0
  loss_config_list:
    - CTCLoss:
    - GuidanceLoss:

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: LMDBDataset
    read_mask: true
    data_dir: ./train_data/rec/train/
    ext_op_transform_idx: 1
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - RecConAug:
          prob: 0.5
          ext_data_num: 2
          image_shape:
            - 32
            - 640
            - 3
      - RecAug: null
      - CTCLabelEncodeWithUnk: null
      - SVTRRecResizeImg:
          image_shape:
            - 3
            - 32
            - 640
          padding: true
      - KeepKeys:
          keep_keys:
            - image
            - label
            - length
            - mask
            - translation
  loader:
    shuffle: true
    batch_size_per_card: 96
    drop_last: true
    num_workers: 12

Eval:
  distributed: true
  dataset:
    name: LMDBDataSet
    read_mask: true
    data_dir: ./train_data/rec/val
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - CTCLabelEncodeWithUnk: null
      - SVTRRecResizeImg:
          image_shape:
            - 3
            - 32
            - 640
          padding: true
      - KeepKeys:
          keep_keys:
            - image
            - label
            - length
            - mask
            - translation
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 384
    num_workers: 8
