Global:
  use_gpu: true
  epoch_num: 72
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec/convnext_ctc/
  save_epoch_step: 3
  # evaluation is run every 2000 iterations
  eval_batch_step: [0, 2000]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: 
  # for data or label process
  character_dict_path: ppocr/utils/dict/nomna_dict.txt
  max_text_length: 27 # CTC does not require max_text_length
  infer_mode: False
  use_space_char: False
  save_res_path: 

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.0005
    name: LinearWarmupCosine
    warmup_steps: 1000
  regularizer:
    name: 'L2'
    factor: 0.05

Architecture:
  model_type: rec
  algorithm: NomNa
  Transform:
  Backbone:
    name: ConvNeXt
    in_channels: 3
    stages: [3,3,6,3]
  Neck:
  Head:
    name: CTCHead
    fc_decay: 0

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/rec/train/
    label_file_list: ["./train_data/rec/rec_gt_train.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - NomNaRecResizeImg:
          image_shape: [3, 432, 32]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 256
    drop_last: True
    num_workers: 8
    
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/rec/train/
    label_file_list: ["./train_data/rec/rec_gt_train.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - NomNaRecResizeImg:
          image_shape: [3, 432, 32]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 256
    drop_last: True
    num_workers: 8