Global:
  use_gpu: true
  epoch_num: 20
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_svtrnet_base_ch_exp_a3/
  save_epoch_step: 1
  eval_batch_step:
    - 10000
    - 2000
  cal_metric_during_train: true
  pretrained_model: null
  checkpoints: null
  
  # vanish gradient combat
  log_grad_norm: true
  #######################
  
  save_inference_dir: null
  use_visualdl: false
  infer_img: null
  character_dict_path: ppocr/utils/dict/PP-Thesis/hisdoc1b.txt
  max_text_length: 40
  infer_mode: false
  use_space_char: false
  save_res_path: null
  use_amp: true
  use_wandb: true
  distributed: true
  d2s_train_image_shape: [3, 32, 584]
  
wandb:
  project: "Rec-Pretraining"
  entity: "trankim147-vnu-hcmus"
  name: "A3"

Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  epsilon: 1.e-8
  weight_decay: 0.05
  no_weight_decay_name: norm
  one_dim_param_no_weight_decay: True
  lr:
    name: LinearWarmupCosine
    learning_rate: 0.0005
    warmup_steps: 2500

Architecture:
  model_type: rec
  algorithm: SVTR
  Transform: null
  Backbone:
    name: SVTRNet
    img_size:
      - 32
      - 584
    out_char_num: 50 # W//4 or W//8 or W/12
    out_channels: 256
    patch_merging: Conv
    patch_size: [4, 8]
    embed_dim:
      - 128
      - 256
      - 384
    depth:
      - 3
      - 6
      - 9
    num_heads:
      - 4
      - 8
      - 12
    mixer:
      - Local
      - Local
      - Local
      - Local
      - Local
      - Local
      - Local
      - Local
      - Global
      - Global
      - Global
      - Global
      - Global
      - Global
      - Global
      - Global
      - Global
      - Global
    local_mixer:
      - - 7
        - 11
      - - 7
        - 11
      - - 7
        - 11
    last_stage: true
    prenorm: false
  Neck:
    name: SequenceEncoder
    encoder_type: reshape
  Head:
    name: CTCHead

Loss:
  name: CTCLoss
  use_focal_loss: true

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: LMDBDataSet
    data_dir: ./train_data/rec/train/
    ext_op_transform_idx: 1
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - RecConAug:
          prob: 0.5
          ext_data_num: 2
          image_shape:
            - 32
            - 584
            - 3
      - RecAug: null
      - CTCLabelEncode: null
      - SVTRRecResizeImg:
          image_shape:
            - 3
            - 32
            - 584
          padding: true
      - KeepKeys:
          keep_keys:
            - image
            - label
            - length
  loader:
    shuffle: true
    batch_size_per_card: 72
    drop_last: true
    num_workers: 12

Eval:
  dataset:
    name: LMDBDataSet
    data_dir: ./train_data/rec/val/
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - CTCLabelEncode: null
      - SVTRRecResizeImg:
          image_shape:
            - 3
            - 32
            - 584
          padding: true
      - KeepKeys:
          keep_keys:
            - image
            - label
            - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 256
    num_workers: 8
