# Example configuration for using NVIDIA DALI operators in PaddleOCR
# This config demonstrates how to use DALI-accelerated data preprocessing

Global:
  use_gpu: true
  epoch_num: 1200
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/det_r50_vd_dali/
  save_epoch_step: 1200
  eval_batch_step: [0,2000]
  cal_metric_during_train: False
  pretrained_model: ./pretrain_models/ResNet50_vd_ssld_pretrained
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./output/det_db/predicts_db.txt

Architecture:
  model_type: det
  algorithm: DB
  Transform:
  Backbone:
    name: ResNet_vd
    layers: 50
  Neck:
    name: DBFPN
    out_channels: 256
  Head:
    name: DBHead
    k: 50

Loss:
  name: DBLoss
  balance_loss: true
  main_loss_type: DiceLoss
  alpha: 5
  beta: 10
  ohem_ratio: 3

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.001
  regularizer:
    name: 'L2'
    factor: 0

PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.7
  max_candidates: 1000
  unclip_ratio: 1.5

Metric:
  name: DetMetric
  main_indicator: hmean

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/icdar2015/text_localization/
    label_file_list:
      - ./train_data/icdar2015/text_localization/train_icdar2015_label.txt
    ratio_list: [1.0]
    # Using DALI operators for GPU-accelerated data preprocessing
    transforms:
      - DALIDecodeImage:  # DALI-accelerated image decoding
          img_mode: BGR
          device: cpu  # Use 'gpu' for GPU acceleration
      - DetLabelEncode:  # Class handling label
      # DALI-accelerated augmentation operators
      - DALIRandomFlip:
          horizontal: true
          vertical: false
          probability: 0.5
      - DALIRandomRotation:
          angle_range: [-10, 10]
          probability: 0.5
      - DALIBrightness:
          brightness_range: [0.8, 1.2]
          probability: 0.3
      - DALIContrast:
          contrast_range: [0.8, 1.2]
          probability: 0.3
      - EastRandomCropData:
          size: [640, 640]
          max_tries: 50
          keep_ratio: true
      - MakeBorderMap:
          shrink_ratio: 0.4
          thresh_min: 0.3
          thresh_max: 0.7
      - MakeShrinkMap:
          shrink_ratio: 0.4
          min_text_size: 8
      - DALINormalizeImage:  # DALI-accelerated normalization
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'threshold_map', 'threshold_mask', 'shrink_map', 'shrink_mask']
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 8
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/icdar2015/text_localization/
    label_file_list:
      - ./train_data/icdar2015/text_localization/test_icdar2015_label.txt
    # Using DALI operators for validation as well
    transforms:
      - DALIDecodeImage:  # DALI-accelerated image decoding
          img_mode: BGR
          device: cpu
      - DetLabelEncode:
      - DetResizeForTest:
      - DALINormalizeImage:  # DALI-accelerated normalization
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'shape', 'polys', 'ignore_tags']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1
    num_workers: 2
