Global:
  model_name: rec_ppocrv5_base_ch_exp_a1.1 # To use static model for inference.
  debug: false
  use_gpu: true
  epoch_num: 5
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_ppocrv5_base_ch_exp_a1.1
  save_epoch_step: 1
  eval_batch_step: [27000000, 2000]
  cal_metric_during_train: true
  calc_epoch_interval: 1
  pretrained_model: null
  checkpoints: null
  save_inference_dir:
  use_visualdl: false
  infer_img: null
  character_dict_path: ./ppocr/utils/dict/PP-Thesis/hisdoc1b.txt
  max_text_length: &max_text_length 40
  infer_mode: false
  use_space_char: false
  use_amp: true
  use_wandb: true
  distributed: true
  save_res_path: null
  huggingface:
    push_to_hub: false
    hf_token: null
    repo_id: "PPThes/checkpoints"
    repo_type: "dataset"
    ignore_patterns: "**/wandb/*"
    run_as_future: true
  d2s_train_image_shape: [3, 32, 640]

wandb:
  project: "Rec-Pretraining"
  entity: "trankim147-vnu-hcmus"
  name: "A1"

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.0005
    warmup_epoch: 1
  regularizer:
    name: L2
    factor: 3.0e-05

Architecture:
  model_type: rec
  algorithm: SVTR_HGNet
  Transform:
  Backbone:
    name: PPHGNetV2_B4
    text_rec: True
    stage_config_rec:
      # in_channels, mid_channels, out_channels, num_blocks, is_downsample, light_block, kernel_size, layer_num, stride
      stage1: [48, 48, 128, 1, True, False, 3, 6, [2, 1]]
      stage2: [128, 96, 512, 1, True, False, 3, 6, [1, 2]]
      stage3: [512, 192, 1024, 3, True, True, 5, 6, [2, 1]]
      stage4: [1024, 384, 2048, 1, True, True, 5, 6, [2, 2]]
  Head:
    name: MultiHead
    head_list:
      - CTCHead:
          Neck:
            name: svtr
            dims: 120
            depth: 2
            hidden_dims: 120
            kernel_size: [1, 3]
            use_guide: True
          Head:
            fc_decay: 0.00001
      - NRTRHead:
          nrtr_dim: 384
          max_text_length: *max_text_length

Loss:
  name: MultiLoss
  loss_config_list:
    - CTCLoss:
    - NRTRLoss:

PostProcess:
  name: CTCLabelDecode

Metric:
  name: DistributedRecMetric
  main_indicator: acc

Train:
  dataset:
    name: MultiScaleLMDBDataSet
    ds_width: false
    data_dir: ./train_data/rec/train
    ext_op_transform_idx: 1
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - RecAug:
      - MultiLabelEncode:
          gtc_encode: NRTRLabelEncode
      - KeepKeys:
          keep_keys:
            - image
            - label_ctc
            - label_gtc
            - length
            - valid_ratio
  sampler:
    name: MultiScaleSampler
    scales: [[640, 32], [640, 48], [640, 64]]
    first_bs: &bs 96
    fix_bs: false
    divided_factor: [8, 16] # w, h
    is_training: True
  loader:
    shuffle: true
    batch_size_per_card: *bs
    drop_last: true
    num_workers: 16

Eval:
  distributed: true
  dataset:
    name: LMDBDataSet
    data_dir: ./train_data/rec/val
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - MultiLabelEncode:
          gtc_encode: NRTRLabelEncode
      - RecResizeImg:
          image_shape: [3, 32, 640]
      - KeepKeys:
          keep_keys:
            - image
            - label_ctc
            - label_gtc
            - length
            - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 384
    num_workers: 8
