Global:
  model_name: PPHGNetV2_B4 # To use static model for inference.
  debug: false
  use_gpu: true
  epoch_num: 20
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_ppocrv5_base_ch_exp_a3
  save_epoch_step: 1
  eval_batch_step: [0, 2000]
  cal_metric_during_train: true
  calc_epoch_interval: 1
  pretrained_model: https://paddle-model-ecology.bj.bcebos.com/paddlex/official_pretrained_model/PP-OCRv5_server_rec_pretrained.pdparams
  checkpoints: null
  save_inference_dir:
  use_visualdl: false
  infer_img: null
  character_dict_path: ./ppocr/utils/dict/PP-Thesis/hisdoc1b_ss1.txt
  max_text_length: 40
  infer_mode: false
  use_space_char: false
  use_amp: true
  use_wandb: true
  distributed: true
  save_res_path: null
  huggingface:
    push_to_hub: false
    hf_token: null
    repo_id: "PPThes/checkpoints"
    repo_type: "dataset"
    ignore_patterns: "**/wandb/*"
    run_as_future: true
  d2s_train_image_shape: [3, 32, 592]

wandb:
  project: "Rec-Pretraining"
  entity: "trankim147-vnu-hcmus"
  name: "A3"

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: LinearWarmupCosine
    learning_rate: 0.001
    warmup_steps: 4
  regularizer:
    name: L2
    factor: 3.0e-05

Architecture:
  model_type: rec
  algorithm: SVTR_HGNet
  Transform:
  Backbone:
    name: PPHGNetV2_B4
    text_rec: True
    stem_channels: [3, 32, 48]
    out_char_num: 74 # for training mode
    out_avg_kernel_size: [4, 2] # for inference mode
    stage_config_rec:
      # in_channels, mid_channels, out_channels, num_blocks, is_downsample, light_block, kernel_size, layer_num, stride
      stage1: [48, 48, 128, 1, False, False, 3, 6, [1, 1]]
      stage2: [128, 96, 512, 1, True, False, 3, 6, [2, 1]]
      stage3: [512, 192, 1024, 3, True, True, 5, 6, [1, 2]]
      stage4: [1024, 384, 2048, 1, True, True, 5, 6, [2, 1]]
  Neck:
    name: SequenceEncoder
    encoder_type: svtr
    dims: 272
    depth: 4
    hidden_dims: 512
    kernel_size: [1, 3]
    drop_rate: 0.1
    attn_drop_rate: 0.1
    drop_path: 0.0
    use_guide: true
    num_heads: 8
  Head:
    name: CTCHead

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: LMDBDataSet
    data_dir: ./train_data/rec/train
    ext_op_transform_idx: 1
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - RecConAug:
          prob: 0.5
          ext_data_num: 2
          image_shape:
            - 32
            - 592
            - 3
      - RecAug:
      - CTCLabelEncode: null
      - SVTRRecResizeImg:
          image_shape:
            - 3
            - 32
            - 592
          padding: true
      - KeepKeys:
          keep_keys:
            - image
            - label
            - length

  loader:
    shuffle: true
    batch_size_per_card: 128
    drop_last: true
    num_workers: 16

Eval:
  dataset:
    name: LMDBDataSet
    data_dir: ./train_data/rec/val
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - CTCLabelEncode: null
      - SVTRRecResizeImg:
          image_shape:
            - 3
            - 32
            - 592
          padding: true
      - KeepKeys:
          keep_keys:
            - image
            - label
            - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 384
    num_workers: 12
