Global:
  model_name: SVTRNet
  debug: false
  use_gpu: true
  epoch_num: 50
  distributed: true
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_svtrnet_base_nom_exp_b2.3.2/
  save_epoch_step: 1
  eval_batch_step: [0, 1818]
  cal_metric_during_train: true
  pretrained_model: ./output/rec_svtrnet_base_ch_exp_a5.1.0/best_accuracy
  checkpoints: null
  character_dict_path: ./ppocr/utils/dict/PP-Thesis/nom_clclab_v2.txt
  save_inference_dir:
  use_visualdl: false
  infer_img: null
  save_res_path: null
  infer_mode: false
  use_space_char: false
  max_text_length: 40
  use_wandb: true
  d2s_train_image_shape: [3, 32, 800]
  
wandb:
  project: "Sino-Nom"
  entity: "trankim147-vnu-hcmus"
  name: "SVTRNet-B2.3.2"

Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  epsilon: 1.e-8
  weight_decay: 0.05
  no_weight_decay_name: norm
  one_dim_param_no_weight_decay: True
  lr:
    name: Cosine
    learning_rate: 0.00015 # 24bs x 2gpus
    warmup_epoch: 5
    eta_min: 0.000005

Architecture:
  model_type: rec
  algorithm: SVTR
  Transform:
    name: TPS
    num_fiducial: 10
    loc_lr: 0.1
    model_name: small
  Backbone:
    name: SVTRNet
    img_size:
      - 32
      - 800
    out_char_num: 40 # W//4 or W//8 or W/12
    out_channels: 256
    patch_merging: Conv
    patch_size: [4, 8]
    drop_rate: 0.2
    last_drop: 0.1
    attn_drop_rate: 0.1
    drop_path_rate: 0.2
    embed_dim:
      - 128
      - 256
      - 384
    depth:
      - 3
      - 6
      - 6
    num_heads:
      - 4
      - 8
      - 12
    mixer:
      - Local
      - Local
      - Local
      - Local
      - Local
      - Local
      - Local
      - Local
      - Global
      - Global
      - Global
      - Global
      - Global
      - Global
      - Global
      - Global
      - Global
      - Global
    local_mixer:
      - - 7
        - 11
      - - 7
        - 11
      - - 7
        - 11
    last_stage: true
    prenorm: true
  Neck:
    name: SequenceEncoder
    encoder_type: reshape
  Head:
    name: CTCHead

Loss:
  name: CTCLoss
  use_focal_loss: true

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/
    label_file_list:
      - ./train_data/Labels/Train/nomna_train.txt
      - ./train_data/Labels/Train/CPNK-vertical_all.txt
      - ./train_data/Labels/Train/HVK_001_vertical_v1_y850_all.txt
      - ./train_data/Labels/Train/RBI_003_02_all.txt
      - ./train_data/Labels/Train/RBI_003_03_all.txt
      - ./train_data/Labels/Train/sac-phong_all.txt
      - ./train_data/Labels/Train/Tale-of-Kieu-1870_all.txt
      - ./train_data/Labels/Train/Tale-of-Kieu-1902_all.txt
      - ./train_data/Labels/Train/ThachSanh-Doc_all.txt 
      - ./train_data/Labels/Train/RB_HuongSonQuanTheAm_replace_all.txt
      - ./train_data/Labels/Train/RCM_001_000_replace_all.txt
      - ./train_data/Labels/Train/RCM_003_000_replace_all.txt
      - ./train_data/Labels/Train/RCM_004_000_replace_all.txt
      - ./train_data/Labels/Train/RCM_005_000_replace_all.txt
      - ./train_data/Labels/Train/RCM_006_000_replace_all.txt
      - ./train_data/Labels/Train/RCM_007_000_replace_all.txt
      - ./train_data/Labels/Train/RCM_009_000_replace_all.txt
      - ./train_data/Labels/Train/RCM_00X_000_replace_all.txt
      - ./train_data/Labels/Train/RCM_010_000_replace_all.txt
      - ./train_data/Labels/Train/RCM_011_000_replace_all.txt
      - ./train_data/Labels/Train/RCM_012_000_replace_all.txt
      - ./train_data/Labels/Train/RCM_013_000_replace_all.txt
      - ./train_data/Labels/Train/RCM_014_000_replace_all.txt
      - ./train_data/Labels/Train/RCM_016_000_replace_all.txt
      - ./train_data/Labels/Train/RCM_019_002_replace_all.txt
      - ./train_data/Labels/Train/RCM_019_003_replace_all.txt
      - ./train_data/Labels/Train/RCM_020_000_replace_all.txt
      - ./train_data/Labels/Train/RCM_021_000_replace_all.txt
    ext_op_transform_idx: 1
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - RecConAug:
          prob: 0.5
          ext_data_num: 2
          image_shape:
            - 32
            - 800
            - 3
      - RecAug:
      - CTCLabelEncode: null
      - SVTRRecResizeImg:
          image_shape:
            - 3
            - 32
            - 800
          padding: true
      - KeepKeys:
          keep_keys:
            - image
            - label
            - length
  loader:
    shuffle: true
    batch_size_per_card: 24
    drop_last: true
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/
    label_file_list:
      - ./train_data/Labels/Validate/nomna_validate.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - CTCLabelEncode: null
      - SVTRRecResizeImg:
          image_shape:
            - 3
            - 32
            - 800
          padding: true
      - KeepKeys:
          keep_keys:
            - image
            - label
            - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 128
    num_workers: 4
