Global:
  model_name: SVTRNet
  debug: false
  use_gpu: true
  epoch_num: 40
  distributed: true
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_svtrnet_base_ch_exp_c1.0.0/
  save_epoch_step: 1
  eval_batch_step: [0, 4882]
  cal_metric_during_train: true

  pretrained_model: ./output/rec_svtrnet_base_ch_exp_a5.1.0/best_accuracy
  checkpoints: null
  character_dict_path: ./ppocr/utils/dict/PP-Thesis/m5hisdoc.txt
  save_inference_dir:
  use_visualdl: false
  infer_img: null
  save_res_path: null
  infer_mode: false
  use_space_char: false
  max_text_length: &max_text_length 60
  use_amp: true
  use_wandb: true
  d2s_train_image_shape: [3, 48, 720]

wandb:
  project: "M5HisDoc"
  entity: "trankim147-vnu-hcmus"
  name: "C1.0.0"

Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  epsilon: 1.e-8
  weight_decay: 0.05
  no_weight_decay_name: norm
  one_dim_param_no_weight_decay: True
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 2

Architecture:
  model_type: rec
  algorithm: SVTR
  Transform: null
  Backbone:
    name: SVTRNet
    img_size:
      - 48
      - 720
    out_char_num: *max_text_length # W//4 or W//8 or W/12
    out_channels: 256
    patch_merging: Conv
    patch_size: [4, 8]
    drop_rate: 0.2
    last_drop: 0.1
    attn_drop_rate: 0.1
    drop_path_rate: 0.2
    embed_dim:
      - 128
      - 256
      - 384
    depth:
      - 3
      - 6
      - 6
    num_heads:
      - 4
      - 8
      - 12
    mixer:
      - Local
      - Local
      - Local
      - Local
      - Local
      - Local
      - Local
      - Local
      - Global
      - Global
      - Global
      - Global
      - Global
      - Global
      - Global
      - Global
      - Global
      - Global
    local_mixer:
      - - 7
        - 11
      - - 7
        - 11
      - - 7
        - 11
    last_stage: true
    prenorm: true
  Neck:
    name: SequenceEncoder
    encoder_type: reshape
  Head:
    name: CTCHead

Loss:
  name: CTCLoss
  use_focal_loss: true

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/
    ext_op_transform_idx: 1
    label_file_list:
      - ./train_data/train.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - RecConAug:
          prob: 0.5
          ext_data_num: 2
          image_shape:
            - 48
            - 720
            - 3
      - RecAug:
      - CTCLabelEncode: null
      - SVTRRecResizeImg:
          image_shape:
            - 3
            - 48
            - 720
          padding: true
      - KeepKeys:
          keep_keys:
            - image
            - label
            - length
  loader:
    shuffle: true
    batch_size_per_card: 48
    drop_last: true
    num_workers: 16

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/
    label_file_list:
      - ./train_data/val.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - CTCLabelEncode: null
      - SVTRRecResizeImg:
          image_shape:
            - 3
            - 48
            - 720
          padding: true
      - KeepKeys:
          keep_keys:
            - image
            - label
            - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 384
    num_workers: 12
