Global:
  model_name: PP-OCRv5_server_det # To use static model for inference.
  debug: false
  use_gpu: true
  epoch_num: &epoch_num 50
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/CLCLab_Vert_Det_PPOCRv5_Finetune_0.6_0.5
  save_epoch_step: 5
  eval_batch_step:
    - 0
    - 602
  cal_metric_during_train: false
  checkpoints:
  pretrained_model: https://paddle-model-ecology.bj.bcebos.com/paddlex/official_pretrained_model/PPHGNetV2_B4_ocr_det.pdparams
  save_inference_dir: null
  use_visualdl: false
  infer_img: null
  save_res_path: null
  distributed: true

wandb:
  project: CLCLab
  entity: "trankim147-vnu-hcmus"
  name: CLCLab_Vert_Det_PPOCRv5_Finetune_0.6_0.5

Architecture:
  model_type: det
  algorithm: DB
  Transform: null
  Backbone:
    name: PPHGNetV2_B4
    det: True
  Neck:
    name: LKPAN
    out_channels: 256
    intracl: true
  Head:
    name: PFHeadLocal
    k: 80
    mode: "large"

Loss:
  name: DBLoss
  balance_loss: true
  main_loss_type: DiceLoss
  alpha: 5
  beta: 30
  ohem_ratio: 3

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.00004
  regularizer:
    name: L2
    factor: 1e-6

PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5

Metric:
  name: DetMetric
  main_indicator: hmean

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/
    label_file_list:
      - ./train_data/VanBia/train.txt
      - ./train_data/Subsample/train.txt
      - ./train_data/HisDoc1B_Subsample/train.txt
    ratio_list: [1.0, 1.0, 1.0]
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - DetLabelEncode: null
      - CopyPaste: null
      - IaaAugment:
          augmenter_args:
            - type: Fliplr
              args:
                p: 0.5
            - type: Affine
              args:
                rotate:
                  - -10
                  - 10
            - type: Resize
              args:
                size:
                  - 0.5
                  - 3
      - EastRandomCropData:
          size:
            - 640
            - 640
          max_tries: 50
          keep_ratio: true
      - MakeBorderMap:
          shrink_ratio: 0.6
          thresh_min: 0.3
          thresh_max: 0.7
          total_epoch: *epoch_num
      - MakeShrinkMap:
          shrink_ratio: 0.5
          min_text_size: 8
          total_epoch: *epoch_num
      - NormalizeImage:
          scale: 1./255.
          mean:
            - 0.485
            - 0.456
            - 0.406
          std:
            - 0.229
            - 0.224
            - 0.225
          order: hwc
      - ToCHWImage: null
      - KeepKeys:
          keep_keys:
            - image
            - threshold_map
            - threshold_mask
            - shrink_map
            - shrink_mask
  loader:
    shuffle: true
    drop_last: false
    batch_size_per_card: 4
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/
    label_file_list:
      - ./train_data/HisDoc1B_Subsample/val.txt
      - ./train_data/VanBia/val.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - DetLabelEncode: null
      - DetResizeForTest:
          limit_side_len: 1280
          limit_type: max
      - NormalizeImage:
          scale: 1./255.
          mean:
            - 0.485
            - 0.456
            - 0.406
          std:
            - 0.229
            - 0.224
            - 0.225
          order: hwc
      - ToCHWImage: null
      - KeepKeys:
          keep_keys:
            - image
            - shape
            - polys
            - ignore_tags
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 1
    num_workers: 2
profiler_options: null
