Global:
  model_name: PP-OCRv5_mobile_rec # To use static model for inference.
  debug: false
  use_gpu: true
  epoch_num: 20
  distributed: true
  eval_batch_step: [10000, 2500]
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_ppocrv5_base_ch_exp_a6.1.1
  save_epoch_step: 1
  cal_metric_during_train: true
  calc_epoch_interval: 1
  
  # vanish gradient combat
  log_grad_norm: true
  #########################
  
  pretrained_model: https://paddle-model-ecology.bj.bcebos.com/paddlex/official_pretrained_model/PP-OCRv5_mobile_rec_pretrained.pdparams
  checkpoints: null
  character_dict_path: ./ppocr/utils/dict/PP-Thesis/hisdoc1b_19k.txt
  save_inference_dir:
  use_visualdl: false
  infer_img: null
  save_res_path: null
  infer_mode: false
  use_space_char: false
  max_text_length: &max_text_length 40
  use_amp: true
  use_wandb: true
  d2s_train_image_shape: [3, 32, 584]

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.0005
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 3.0e-05

Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Transform:
  Backbone:
    name: PPLCNetV3
    scale: 0.95
    out_char_num: 40
    glb_avg_kernel: [2, 2]
    net_config:
      # k, in_c, out_c, s, use_se
      blocks2: [[3, 16, 32, 1, False]]
      blocks3: [[3, 32, 64, 1, False], [3, 64, 64, 1, False]]
      blocks4: [[3, 64, 128, [2, 1], False], [3, 128, 128, 1, False]]
      blocks5:
        [
          [3, 128, 256, [1, 2], False],
          [5, 256, 256, 1, False],
          [5, 256, 256, 1, False],
          [5, 256, 256, 1, False],
          [5, 256, 256, 1, False],
        ]
      blocks6:
        [
          [5, 256, 512, [2, 1], True],
          [5, 512, 512, 1, True],
          [5, 512, 512, [2, 1], False],
          [5, 512, 512, 1, False],
        ]
  Head:
    name: MultiHead
    head_list:
      - CTCHead:
          Neck:
            name: svtr
            dims: 160
            depth: 2
            hidden_dims: 160
            kernel_size: [1, 3]
            use_guide: True
          Head:
            fc_decay: 0.00001
      - NRTRHead:
          nrtr_dim: 384
          max_text_length: *max_text_length

Loss:
  name: MultiLoss
  loss_config_list:
    - CTCLoss:
    - NRTRLoss:

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: UnifiedMultiScaleLMDBDataSet
    ds_width: false
    data_dir: ./train_data/rec/full
    val_ids: ./train_data/rec/val_ids.json
    ext_op_transform_idx: 1
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - RecConAug:
          prob: 0.5
          ext_data_num: 2
          image_shape: [32, 584, 3]
          max_text_length: *max_text_length
      - RecAug:
      - MultiLabelEncode:
          gtc_encode: NRTRLabelEncode
      - KeepKeys:
          keep_keys:
            - image
            - label_ctc
            - label_gtc
            - length
            - valid_ratio
  sampler:
    name: MultiScaleSampler
    scales: [[584, 32], [584, 48], [584, 64]]
    first_bs: &bs 128
    fix_bs: false
    divided_factor: [8, 16] # w, h
    is_training: True
  loader:
    shuffle: true
    batch_size_per_card: *bs
    drop_last: true
    num_workers: 8
Eval:
  dataset:
    name: UnifiedLMDBDataSet
    data_dir: ./train_data/rec/full
    val_ids: ./train_data/rec/val_ids.json
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - MultiLabelEncode:
          gtc_encode: NRTRLabelEncode
      - RecResizeImg:
          image_shape: [3, 48, 584]
      - KeepKeys:
          keep_keys:
            - image
            - label_ctc
            - label_gtc
            - length
            - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 128
    num_workers: 4
