Global:
  use_gpu: True
  epoch_num: 25
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec/nomnanet_none_transformer/
  save_epoch_step: 5
  # evaluation is run every 2000 iterations
  eval_batch_step: [0, 200]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img:
  # for data or label process
  character_dict_path: ppocr/utils/dict/nomna_dict.txt
  max_text_length: 25
  infer_mode: False
  use_space_char: False
  save_res_path: ./output/rec/predicts_nomnanet_none_transformer.txt

Optimizer:
  name: Adadelta
  lr:
    learning_rate: 1.0
  regularizer:
    name: 'L2'
    factor: 0

Architecture:
  model_type: rec
  algorithm: NomNaDecoder
  Transform:
  Backbone:
    name: NomNaNet
  Neck:
  Head:
    name: NomNaTransformer
    d_model: 512
    nhead: 1
    num_encoder_layers: 2
    num_decoder_layers: 2
    dim_feedforward: 512
    attention_dropout_rate: 0.1

Loss:
  name: NomNaTransformerLoss
  smoothing: false

PostProcess:
  name: NomNaTransformerLabelDecode

Metric:
  name: RecMetric
  main_indicator: "char_acc"

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/rec/train/
    label_file_list: ["./train_data/rec/rec_gt_train.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - NomNaTransformerLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 48, 432]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    batch_size_per_card: 256
    drop_last: True
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/rec/val/
    label_file_list: ["./train_data/rec/rec_gt_val.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - NomNaTransformerLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 48, 432]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 256
    num_workers: 4
