Global:
  debug: false
  use_gpu: true
  epoch_num: 50
  distributed: true
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_svtrnet_large_ch_exp_c1.0.0/
  save_epoch_step: 1
  
  # evaluation is run every 2000 iterations after the 0th iteration
  eval_batch_step: [0, 95624]
  cal_metric_during_train: true
  pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: false
  infer_img: null
  character_dict_path: ./ppocr/utils/dict/PP-Thesis/hisdoc1b_22k.txt
  max_text_length: &max_text_length 40
  infer_mode: false
  use_space_char: false
  save_res_path: null
  use_wandb: true
  d2s_train_image_shape: [3, 32, 640]

wandb:
  project: "HisDoc1B-30M"
  entity: "trankim147-vnu-hcmus"
  name: "C1.0.0"

Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.99
  epsilon: 1.0e-08
  weight_decay: 0.05
  no_weight_decay_name: norm pos_embed char_node_embed pos_node_embed char_pos_embed vis_pos_embed
  one_dim_param_no_weight_decay: true
  lr:
    name: Cosine
    learning_rate: 0.0003 # 8gpus 42bs
    warmup_epoch: 2

Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Transform: null
  Backbone:
    name: SVTRNet
    img_size:
      - 32
      - 640
    out_char_num: *max_text_length
    out_channels: 384
    patch_merging: Conv
    drop_rate: 0.15
    last_drop: 0.1
    attn_drop_rate: 0.1
    drop_path_rate: 0.1
    embed_dim: [192, 256, 512]
    depth: [6, 6, 9]
    num_heads: [6, 8, 16]
    mixer:
      [
        "Conv",
        "Conv",
        "Conv",
        "Conv",
        "Conv",
        "Conv",
        "Conv",
        "Conv",
        "Conv",
        "Global",
        "Global",
        "Global",
        "Global",
        "Global",
        "Global",
        "Global",
        "Global",
        "Global",
        "Global",
        "Global",
        "Global",
      ]
    local_mixer: [[5, 5], [5, 5], [5, 5]]
    last_stage: True
    prenorm: True
  Neck:
    name: SequenceEncoder
    encoder_type: reshape
  Head:
    name: CTCHead

Loss:
  name: CTCLoss
  use_focal_loss: true

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: true

Train:
  dataset:
    name: UnifiedLMDBDataSet
    data_dir: ./train_data/rec/full
    val_ids: ./train_data/rec/val_ids.json
    ext_op_transform_idx: 1
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - RecConAug:
          prob: 0.5
          ext_data_num: 2
          image_shape:
            - 32
            - 640
            - 3
      - RecAug:
      - CTCLabelEncode: null
      - SVTRRecResizeImg:
          image_shape:
            - 3
            - 32
            - 640
          padding: true
      - KeepKeys:
          keep_keys:
            - image
            - label
            - length
  loader:
    shuffle: true
    batch_size_per_card: 40
    drop_last: true
    num_workers: 12

Eval:
  dataset:
    name: UnifiedLMDBDataSet
    data_dir: ./train_data/rec/full
    val_ids: ./train_data/rec/val_ids.json
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - CTCLabelEncode: null
      - SVTRRecResizeImg:
          image_shape:
            - 3
            - 32
            - 640
          padding: true
      - KeepKeys:
          keep_keys:
            - image
            - label
            - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 640
    num_workers: 8
