Global:
  use_gpu: True
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_mv3_tps_bilstm_att/
  save_epoch_step: 1
  # evaluation is run every 2000 iterations
  eval_batch_step: [0, 2000]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img:
  # for data or label process
  character_dict_path: ppocr/utils/dict/PP-Thesis/nom_clclab_v2.txt
  max_text_length: 40
  infer_mode: False
  use_space_char: False
  save_res_path:

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.0001
  regularizer:
    name: 'L2'
    factor: 0.00001

Architecture:
  model_type: rec
  algorithm: RARE
  Transform:
    name: TPS
    num_fiducial: 20
    loc_lr: 0.1
    model_name: small
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
  Neck:
    name: SequenceEncoder
    encoder_type: rnn 
    hidden_size: 128
  Head:
    name: AttentionHead
    hidden_size: 256   
    max_length: 40
    

Loss:
  name: AttentionLoss

PostProcess:
  name: AttnLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/
    label_file_list:
      - ./train_data/Labels/Train/nomna_train.txt
      - ./train_data/Labels/Train/CPNK-vertical_all.txt
      - ./train_data/Labels/Train/HVK_001_vertical_v1_y850_all.txt
      - ./train_data/Labels/Train/RBI_003_02_all.txt
      - ./train_data/Labels/Train/RBI_003_03_all.txt
      - ./train_data/Labels/Train/sac-phong_all.txt
      - ./train_data/Labels/Train/Tale-of-Kieu-1870_all.txt
      - ./train_data/Labels/Train/Tale-of-Kieu-1902_all.txt
      - ./train_data/Labels/Train/ThachSanh-Doc_all.txt
      - ./train_data/Labels/Train/NomCongGiao/RB_HuongSonQuanTheAm_train.txt
      - ./train_data/Labels/Train/NomCongGiao/RCM_001_000_train.txt
      - ./train_data/Labels/Train/NomCongGiao/RCM_003_000_train.txt
      - ./train_data/Labels/Train/NomCongGiao/RCM_004_000_train.txt
      - ./train_data/Labels/Train/NomCongGiao/RCM_005_000_train.txt
      - ./train_data/Labels/Train/NomCongGiao/RCM_006_000_train.txt
      - ./train_data/Labels/Train/NomCongGiao/RCM_007_000_train.txt
      - ./train_data/Labels/Train/NomCongGiao/RCM_009_000_train.txt
      - ./train_data/Labels/Train/NomCongGiao/RCM_00X_000_train.txt
      - ./train_data/Labels/Train/NomCongGiao/RCM_010_000_train.txt
      - ./train_data/Labels/Train/NomCongGiao/RCM_011_000_train.txt
      - ./train_data/Labels/Train/NomCongGiao/RCM_012_000_train.txt
      - ./train_data/Labels/Train/NomCongGiao/RCM_013_000_train.txt
      - ./train_data/Labels/Train/NomCongGiao/RCM_014_000_train.txt
      - ./train_data/Labels/Train/NomCongGiao/RCM_016_000_train.txt
      - ./train_data/Labels/Train/NomCongGiao/RCM_019_002_train.txt
      - ./train_data/Labels/Train/NomCongGiao/RCM_019_003_train.txt
      - ./train_data/Labels/Train/NomCongGiao/RCM_020_000_train.txt
      - ./train_data/Labels/Train/NomCongGiao/RCM_021_000_train.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - AttnLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 48, 960]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 32
    drop_last: True
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/
    label_file_list:
      - ./train_data/Labels/Validate/nomna_validate.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - AttnLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 48, 960]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 256
    num_workers: 4
